version: '3'

services:

  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mariadb:
    image: mariadb:10.6
    env_file: .env
    container_name: mariadb
    restart: unless-stopped
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker-volumes/db/dolibarr_db:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=dolibarr
      # - MYSQL_USER=dolibarr
      # - MYSQL_PASSWORD=dolibarr
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes

  dolibarr:
    image: upshift/dolibarr:14.0
    env_file: .env
    container_name: dolibarr
    restart: unless-stopped
    depends_on:
        - mariadb
    ports:
        - "8200:80"
    environment:
      # - DOLI_ADMIN_LOGIN=admin
      # - DOLI_ADMIN_PASSWORD=p4ssw0rd
      # - DOLI_DB_HOST=mariadb
      # - DOLI_DB_NAME=dolibarr
      # - DOLI_DB_USER=dolibarr
      # - DOLI_DB_PASSWORD=dolibarr
      - TZ=Europe/Madrid 
      - LANG=es_ES
      - VIRTUAL_HOST=${VIRTUAL.HOST}
      - LETSENCRYPT_HOST=${SSL.HOST}
      - LETSENCRYPT_EMAIL=${SSL.EMAIL}
    volumes:
      - ./docker-volumes/dolibar/doli_html:/var/www/html
      - ./docker-volumes/dolibar/doli_docs:/var/www/documents

volumes:
  certs:
  html:
  vhostd:
  confd:
     
